accsi/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('user.urls')),
    path('modalidade/', include('modality.urls')),
    path('alunos/', include('student.urls')),
]

modality/urls.py
from django.urls import path

from .views import ListModality


app_name = 'modality'

urlpatterns = [
    path('', ListModality.as_view(), name='list'),
]

student/urls.py
from django.urls import path

from .views import ListStudents, CreateStudent, UpdateStudent


app_name = 'student'

urlpatterns = [
    path('', ListStudents.as_view(), name='list'),
    path('cadastrar/', CreateStudent.as_view(), name='create'),
    path('alterar/<int:pk>', UpdateStudent.as_view(), name='update'),
]

user/urls.py
from django.urls import path

from .views import CreateUser, UpdateUser, ListUser


app_name = 'user'

urlpatterns = [
    path('cadastrar/<int:meu>/', CreateUser.as_view(), name='create'),
    path('alterar/<int:pk>/', UpdateUser.as_view(), name='update'),
    path('usuarios/', ListUser.as_view(), name='list'),
]

activity/models.py
from django.db import models

from modality.models import Modality


class Activity(models.Model):

    code = models.CharField(max_length=5)
    modality = models.ForeignKey(Modality, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=255)
    workload_min = models.IntegerField()
    workload_max = models.IntegerField()
    use = models.IntegerField()

    def __str__(self):
        return '{}'.format(self.code)

modality/models.py
from django.db import models


class Modality(models.Model):

    name = models.CharField(max_length=15)
    description = models.TextField(max_length=255)


    def __str__(self):
        return "{}".format(self.name)

student/models.py
from django.db import models


class Student(models.Model):

    registration = models.CharField('Matrícula', max_length=8)
    name = models.CharField('Nome', max_length=50)
    email = models.EmailField()
    phone_number = models.CharField('Telefone', max_length=11)

    def __str__(self):
        return '{}'.format(self.name)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    def __str__(self):
        return "{} ({})".format(self.first_name, self.last_name)

activity/views.py
from django.shortcuts import render

# Create your views here.

modality/views.py
from django.views.generic.list import ListView

from .models import Modality


class ListModality(ListView):
    template_name = 'modality/modality_list.html'
    model = Modality
    context_object_name = 'modalities'

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=None, **kwargs)
        context['page_title'] = 'Modalidades'

        return context

student/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from .models import Student


class CreateStudent(CreateView):
    template_name = 'student/student_form.html'
    model = Student
    fields = ['registration', 'name', 'email', 'phone_number']
    success_url = reverse_lazy('student:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Alunos'

        return context


class UpdateStudent(UpdateView):
    template_name = 'student/student_form.html'
    model = Student
    fields = ['registration', 'name', 'email', 'phone_number']
    success_url = reverse_lazy('student:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Alunos'

        return context

class ListStudents(ListView):
    template_name = 'student/student_list.html'
    model = Student
    context_object_name = 'students'

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=None, **kwargs)
        context['page_title'] = 'Alunos'

        return context

user/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from .models import User


class CreateUser(CreateView):
    template_name = 'user/user_form.html'
    model = User
    fields = ['email', 'username', 'first_name', 'last_name', 'password']
    success_url = reverse_lazy('user:list')

    def dispatch(self, request, *args, **kwargs):
        self.aluno = kwargs.get('meu', None)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Cadastrar' + str(self.aluno)

        return context

    def form_valid(self, form):
        # form.instance.email = 'haro'
        return super().form_valid(form)


class UpdateUser(UpdateView):
    template_name = 'user/user_form.html'
    model = User
    fields = ['email', 'username', 'first_name', 'last_name', 'password']
    success_url = reverse_lazy('user:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Alterar Usuário'

        return context


class ListUser(ListView):
    template_name = 'user/user_list.html'
    model = User
    context_object_name = 'users'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Usuários'

        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=2)
        return queryset

templates/modality/modality_list.html
{% extends 'template_main.html' %}
{% load static %}

{% block main %}
    {% for modality in modalities %}
        <p><a href="">{{ modality.pk }} {{ modality.name }}</a></p>
    {% empty %}
        <p>Não há Modalidades cadastradas.</p>
    {% endfor %}
{% endblock main %}

templates/student/student_form.html
{% extends 'template_main.html' %}
{% load static %}
{% load widget_tweaks %}

{% block page_title %}
{{ page_title }}
{% endblock page_title %}

{% block main %}
    <form method="post">
        {% csrf_token %}

        <label for="{{ form.registration.id_for_label }}">{{ form.registration.label }}:</label>
        {% render_field form.registration %}
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
        {% render_field form.name %}
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
        {% render_field form.email %}
        <label for="{{ form.phone_number.id_for_label }}">{{ form.phone_number.label }}:</label>
        {% render_field form.phone_number %}

        <button type="submit">Salvar</button>
        <a href="{% url 'student:list' %}">Cancelar</a>
    </form>
{% endblock main %}

templates/student/student_list.html
{% extends 'template_main.html' %}
{% load static %}

{% block main %}
    <a href="{% url 'student:create' %}">Adicionar</a>
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>Matrícula:</th>
            <th>Nome:</th>
            <th>Email:</th>
            <th>Telefone</th>
            <th>Opçoes:</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.pk }}</td>
                <td>{{ student.registration }}</td>
                <td>{{ student.name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.phone_number }}</td>
                <td>
                    <a href="{% url 'student:update' student.pk %}">Alterar</a>
                </td>
            </tr>
        {% empty %}

        {% endfor %}
        </tbody>
    </table>
{% endblock main %}

templates/template_main.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title %}{% endblock page_title %}</title>
</head>
<body>
{% block main %}

{% endblock main %}

{% block scripts %}

{% endblock scripts %}
</body>
</html>

templates/user/user_form.html
{% extends 'template_main.html' %}
{% load static %}
{% load widget_tweaks %}

{% block page_title %}
{{ page_title }}
{% endblock page_title %}

{% block main %}
    <form method="post">
        {% csrf_token %}

        {{ mess }}

        <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}:</label>
        {% render_field form.first_name %}
        <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}:</label>
        {% render_field form.last_name %}
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
        {% render_field form.email %}
        <label for="{{ form.username.id_for_label }}">{{ form.username.label }}:</label>
        {% render_field form.username %}
        <label for="{{ form.password.id_for_label }}">{{ form.password.label }}:</label>
        {% render_field form.password %}

        <button type="submit">Salvar</button>
        <a href="{% url 'user:list' %}">Cancelar</a>
    </form>
{% endblock main %}

templates/user/user_list.html
{% extends 'template_main.html' %}
{% load static %}

{% block main %}
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome:</th>
            <th>Usuário:</th>
            <th>Email:</th>
            <th>Opçoes:</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.pk }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <a href="{% url 'user:update' user.pk %}">Alterar</a>
                </td>
            </tr>
        {% empty %}

        {% endfor %}
        </tbody>
    </table>
{% endblock main %}